### ISSUE TITLE
No such file or directory: 'ott3.3/family.tsv'

### ISSUE THREAD

**Issue by cfz1998** [OpenTreeOfLife/python-opentree#21]
When i  follow the "bird_families = taxonomy_helpers.get_ott_ids_group_and_rank(group_ott_id=aves, 
                                                            rank='family', 
                                                            taxonomy_file='ott3.3/taxonomy.tsv')"
I got a error! " [Errno 2] No such file or directory: 'ott3.3/family.tsv" . How can i get the right result?
Thanks a lot!

**Comment by snacktavish** [comment]
Sorry about that - that error is because in the previous line 
`taxonomy_helpers.download_taxonomy_file(version = 3.2, loc = '../..')`
I neglected to update the tutorial to use the most recent taxonomy
If you change that to:
`taxonomy_helpers.download_taxonomy_file(version = 3.3, loc = '../..')`
it should work!

I'll update the tutorial now.

**Comment by snacktavish** [comment]
https://github.com/OpenTreeOfLife/python-opentree/pull/22
Fixed here

**Comment by cfz1998** [comment]
> #22 Fixed here

Thank you! Sir
